### PR TITLE
View product detail

### PR DESCRIPTION
**Pull request by hannahmneal**
# Description

Product details are now visible when viewing the list of products and the details of a single product can be viewed after clicking _Details_ for a specific product from the product list. There is also an _Add to Order_ link listed for all products in the product list, and an _Add to Order_ button in the details view for a selected product.

Fixes # (issue)

https://github.com/nss-copper-dragonflies/BangazonSite/issues/2

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

```git fetch --all```
```git checkout view-product-details```
After logging in with your credentials, navigate your URL to localhost:5000/Products/Index and verify you can see the list of products with the _Add to Order_ link being displayed with the _Edit_ and _Details_ links.
Click on the _Details_ link for a given product and verify that you are routed to the product details view for the product you selected and that a green _Add to Order_ button is available with the _Edit_ and _Back to List_ links.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by asiamcarter — CHANGES_REQUESTED** [review]
Product link does not appear in the nav bar when logged in. Otherwise, everything works!

**Review by asiamcarter — APPROVED** [review]

**Comment by hannahmneal** [comment]
> Product link does not appear in the nav bar when logged in. Otherwise, everything works!

I updated the testing instructions to account for this. Thank you!

**Review by bramosja — CHANGES_REQUESTED** [review]
Looks good, but don't forget to update the README and add your name to the "Authors" on the ProductsController

**Review by leahhoefling — APPROVED** [review]
Good job!

**Review by bramosja — APPROVED** [review]
Great!

**Pull request merged**
